# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.srcs/sources_1/ip/axis_ila_2/axis_ila_2.xci
# IP: The module: 'axis_ila_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/bd_f170_0.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f170_0 || ORIG_REF_NAME==bd_f170_0} -quiet] -quiet

# IP: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_0/bd_f170_0_axis_dbg_stub_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f170_0_axis_dbg_stub_0 || ORIG_REF_NAME==bd_f170_0_axis_dbg_stub_0} -quiet] -quiet

# IP: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_1/bd_f170_0_xlconstant_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f170_0_xlconstant_0 || ORIG_REF_NAME==bd_f170_0_xlconstant_0} -quiet] -quiet

# IP: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_2/bd_f170_0_axis_ila_intf_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f170_0_axis_ila_intf_0 || ORIG_REF_NAME==bd_f170_0_axis_ila_intf_0} -quiet] -quiet

# IP: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_3/bd_f170_0_axis_cap_ctrl_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f170_0_axis_cap_ctrl_0 || ORIG_REF_NAME==bd_f170_0_axis_cap_ctrl_0} -quiet] -quiet

# IP: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_4/bd_f170_0_axis_mu0_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f170_0_axis_mu0_0_0 || ORIG_REF_NAME==bd_f170_0_axis_mu0_0_0} -quiet] -quiet

# IP: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_5/bd_f170_0_axis_mu1_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f170_0_axis_mu1_0_0 || ORIG_REF_NAME==bd_f170_0_axis_mu1_0_0} -quiet] -quiet

# IP: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_6/bd_f170_0_axis_mu2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f170_0_axis_mu2_0_0 || ORIG_REF_NAME==bd_f170_0_axis_mu2_0_0} -quiet] -quiet

# IP: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_7/bd_f170_0_axis_mu3_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f170_0_axis_mu3_0_0 || ORIG_REF_NAME==bd_f170_0_axis_mu3_0_0} -quiet] -quiet

# IP: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_8/bd_f170_0_axis_mu4_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f170_0_axis_mu4_0_0 || ORIG_REF_NAME==bd_f170_0_axis_mu4_0_0} -quiet] -quiet

# IP: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_9/bd_f170_0_axis_mu5_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f170_0_axis_mu5_0_0 || ORIG_REF_NAME==bd_f170_0_axis_mu5_0_0} -quiet] -quiet

# IP: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_10/bd_f170_0_axis_mu6_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f170_0_axis_mu6_0_0 || ORIG_REF_NAME==bd_f170_0_axis_mu6_0_0} -quiet] -quiet

# IP: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_11/bd_f170_0_axis_mu7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f170_0_axis_mu7_0_0 || ORIG_REF_NAME==bd_f170_0_axis_mu7_0_0} -quiet] -quiet

# IP: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_12/bd_f170_0_axis_mu8_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f170_0_axis_mu8_0_0 || ORIG_REF_NAME==bd_f170_0_axis_mu8_0_0} -quiet] -quiet

# IP: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_13/bd_f170_0_axis_mu9_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f170_0_axis_mu9_0_0 || ORIG_REF_NAME==bd_f170_0_axis_mu9_0_0} -quiet] -quiet

# IP: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_14/bd_f170_0_axis_mu10_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f170_0_axis_mu10_0_0 || ORIG_REF_NAME==bd_f170_0_axis_mu10_0_0} -quiet] -quiet

# IP: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_15/bd_f170_0_axis_mu11_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f170_0_axis_mu11_0_0 || ORIG_REF_NAME==bd_f170_0_axis_mu11_0_0} -quiet] -quiet

# IP: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_16/bd_f170_0_axis_mu12_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f170_0_axis_mu12_0_0 || ORIG_REF_NAME==bd_f170_0_axis_mu12_0_0} -quiet] -quiet

# IP: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_17/bd_f170_0_axis_mu13_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f170_0_axis_mu13_0_0 || ORIG_REF_NAME==bd_f170_0_axis_mu13_0_0} -quiet] -quiet

# IP: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_18/bd_f170_0_axis_dbg_sync_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f170_0_axis_dbg_sync_2_0 || ORIG_REF_NAME==bd_f170_0_axis_dbg_sync_2_0} -quiet] -quiet

# IP: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_19/bd_f170_0_axis_dbg_sync_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f170_0_axis_dbg_sync_3_0 || ORIG_REF_NAME==bd_f170_0_axis_dbg_sync_3_0} -quiet] -quiet

# IP: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_20/bd_f170_0_axis_dbg_sync_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f170_0_axis_dbg_sync_4_0 || ORIG_REF_NAME==bd_f170_0_axis_dbg_sync_4_0} -quiet] -quiet

# IP: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_21/bd_f170_0_axis_dbg_sync_5_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f170_0_axis_dbg_sync_5_0 || ORIG_REF_NAME==bd_f170_0_axis_dbg_sync_5_0} -quiet] -quiet

# IP: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_22/bd_f170_0_axis_dbg_sync_6_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f170_0_axis_dbg_sync_6_0 || ORIG_REF_NAME==bd_f170_0_axis_dbg_sync_6_0} -quiet] -quiet

# IP: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_23/bd_f170_0_tc_axis_mu0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f170_0_tc_axis_mu0_0 || ORIG_REF_NAME==bd_f170_0_tc_axis_mu0_0} -quiet] -quiet

# IP: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_24/bd_f170_0_cc_axis_mu0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f170_0_cc_axis_mu0_0 || ORIG_REF_NAME==bd_f170_0_cc_axis_mu0_0} -quiet] -quiet

# IP: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_25/bd_f170_0_cc_axis_mu1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f170_0_cc_axis_mu1_0 || ORIG_REF_NAME==bd_f170_0_cc_axis_mu1_0} -quiet] -quiet

# IP: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_26/bd_f170_0_cc_axis_mu2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f170_0_cc_axis_mu2_0 || ORIG_REF_NAME==bd_f170_0_cc_axis_mu2_0} -quiet] -quiet

# IP: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_27/bd_f170_0_cc_axis_mu3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f170_0_cc_axis_mu3_0 || ORIG_REF_NAME==bd_f170_0_cc_axis_mu3_0} -quiet] -quiet

# IP: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_28/bd_f170_0_axis_itct_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f170_0_axis_itct_0 || ORIG_REF_NAME==bd_f170_0_axis_itct_0} -quiet] -quiet

# IP: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_29/bd_f170_0_axis_ila_pp_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f170_0_axis_ila_pp_0 || ORIG_REF_NAME==bd_f170_0_axis_ila_pp_0} -quiet] -quiet

# IP: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_30/bd_f170_0_axis_mem_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f170_0_axis_mem_0 || ORIG_REF_NAME==bd_f170_0_axis_mem_0} -quiet] -quiet

# XDC: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_4/axis_mu_v1_0/constraints/axis_mu_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_f170_0_axis_mu0_0_0 || ORIG_REF_NAME==bd_f170_0_axis_mu0_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_5/axis_mu_v1_0/constraints/axis_mu_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_f170_0_axis_mu1_0_0 || ORIG_REF_NAME==bd_f170_0_axis_mu1_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_6/axis_mu_v1_0/constraints/axis_mu_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_f170_0_axis_mu2_0_0 || ORIG_REF_NAME==bd_f170_0_axis_mu2_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_7/axis_mu_v1_0/constraints/axis_mu_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_f170_0_axis_mu3_0_0 || ORIG_REF_NAME==bd_f170_0_axis_mu3_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_8/axis_mu_v1_0/constraints/axis_mu_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_f170_0_axis_mu4_0_0 || ORIG_REF_NAME==bd_f170_0_axis_mu4_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_9/axis_mu_v1_0/constraints/axis_mu_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_f170_0_axis_mu5_0_0 || ORIG_REF_NAME==bd_f170_0_axis_mu5_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_10/axis_mu_v1_0/constraints/axis_mu_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_f170_0_axis_mu6_0_0 || ORIG_REF_NAME==bd_f170_0_axis_mu6_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_11/axis_mu_v1_0/constraints/axis_mu_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_f170_0_axis_mu7_0_0 || ORIG_REF_NAME==bd_f170_0_axis_mu7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_12/axis_mu_v1_0/constraints/axis_mu_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_f170_0_axis_mu8_0_0 || ORIG_REF_NAME==bd_f170_0_axis_mu8_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_13/axis_mu_v1_0/constraints/axis_mu_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_f170_0_axis_mu9_0_0 || ORIG_REF_NAME==bd_f170_0_axis_mu9_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_14/axis_mu_v1_0/constraints/axis_mu_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_f170_0_axis_mu10_0_0 || ORIG_REF_NAME==bd_f170_0_axis_mu10_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_15/axis_mu_v1_0/constraints/axis_mu_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_f170_0_axis_mu11_0_0 || ORIG_REF_NAME==bd_f170_0_axis_mu11_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_16/axis_mu_v1_0/constraints/axis_mu_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_f170_0_axis_mu12_0_0 || ORIG_REF_NAME==bd_f170_0_axis_mu12_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_17/axis_mu_v1_0/constraints/axis_mu_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_f170_0_axis_mu13_0_0 || ORIG_REF_NAME==bd_f170_0_axis_mu13_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_23/axis_mu_v1_0/constraints/axis_mu_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_f170_0_tc_axis_mu0_0 || ORIG_REF_NAME==bd_f170_0_tc_axis_mu0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_24/axis_mu_v1_0/constraints/axis_mu_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_f170_0_cc_axis_mu0_0 || ORIG_REF_NAME==bd_f170_0_cc_axis_mu0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_25/axis_mu_v1_0/constraints/axis_mu_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_f170_0_cc_axis_mu1_0 || ORIG_REF_NAME==bd_f170_0_cc_axis_mu1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_26/axis_mu_v1_0/constraints/axis_mu_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_f170_0_cc_axis_mu2_0 || ORIG_REF_NAME==bd_f170_0_cc_axis_mu2_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_27/axis_mu_v1_0/constraints/axis_mu_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_f170_0_cc_axis_mu3_0 || ORIG_REF_NAME==bd_f170_0_cc_axis_mu3_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/bd_f170_0_ooc.xdc

# XDC: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/axis_ila_v1_2/constraints/axis_ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_ila_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/axis_ila_v1_2/constraints/axis_ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_ila_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/axis_ila_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_ila_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.srcs/sources_1/ip/axis_ila_2/axis_ila_2.xci
# IP: The module: 'axis_ila_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/bd_f170_0.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f170_0 || ORIG_REF_NAME==bd_f170_0} -quiet] -quiet

# IP: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_0/bd_f170_0_axis_dbg_stub_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f170_0_axis_dbg_stub_0 || ORIG_REF_NAME==bd_f170_0_axis_dbg_stub_0} -quiet] -quiet

# IP: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_1/bd_f170_0_xlconstant_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f170_0_xlconstant_0 || ORIG_REF_NAME==bd_f170_0_xlconstant_0} -quiet] -quiet

# IP: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_2/bd_f170_0_axis_ila_intf_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f170_0_axis_ila_intf_0 || ORIG_REF_NAME==bd_f170_0_axis_ila_intf_0} -quiet] -quiet

# IP: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_3/bd_f170_0_axis_cap_ctrl_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f170_0_axis_cap_ctrl_0 || ORIG_REF_NAME==bd_f170_0_axis_cap_ctrl_0} -quiet] -quiet

# IP: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_4/bd_f170_0_axis_mu0_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f170_0_axis_mu0_0_0 || ORIG_REF_NAME==bd_f170_0_axis_mu0_0_0} -quiet] -quiet

# IP: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_5/bd_f170_0_axis_mu1_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f170_0_axis_mu1_0_0 || ORIG_REF_NAME==bd_f170_0_axis_mu1_0_0} -quiet] -quiet

# IP: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_6/bd_f170_0_axis_mu2_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f170_0_axis_mu2_0_0 || ORIG_REF_NAME==bd_f170_0_axis_mu2_0_0} -quiet] -quiet

# IP: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_7/bd_f170_0_axis_mu3_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f170_0_axis_mu3_0_0 || ORIG_REF_NAME==bd_f170_0_axis_mu3_0_0} -quiet] -quiet

# IP: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_8/bd_f170_0_axis_mu4_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f170_0_axis_mu4_0_0 || ORIG_REF_NAME==bd_f170_0_axis_mu4_0_0} -quiet] -quiet

# IP: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_9/bd_f170_0_axis_mu5_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f170_0_axis_mu5_0_0 || ORIG_REF_NAME==bd_f170_0_axis_mu5_0_0} -quiet] -quiet

# IP: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_10/bd_f170_0_axis_mu6_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f170_0_axis_mu6_0_0 || ORIG_REF_NAME==bd_f170_0_axis_mu6_0_0} -quiet] -quiet

# IP: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_11/bd_f170_0_axis_mu7_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f170_0_axis_mu7_0_0 || ORIG_REF_NAME==bd_f170_0_axis_mu7_0_0} -quiet] -quiet

# IP: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_12/bd_f170_0_axis_mu8_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f170_0_axis_mu8_0_0 || ORIG_REF_NAME==bd_f170_0_axis_mu8_0_0} -quiet] -quiet

# IP: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_13/bd_f170_0_axis_mu9_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f170_0_axis_mu9_0_0 || ORIG_REF_NAME==bd_f170_0_axis_mu9_0_0} -quiet] -quiet

# IP: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_14/bd_f170_0_axis_mu10_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f170_0_axis_mu10_0_0 || ORIG_REF_NAME==bd_f170_0_axis_mu10_0_0} -quiet] -quiet

# IP: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_15/bd_f170_0_axis_mu11_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f170_0_axis_mu11_0_0 || ORIG_REF_NAME==bd_f170_0_axis_mu11_0_0} -quiet] -quiet

# IP: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_16/bd_f170_0_axis_mu12_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f170_0_axis_mu12_0_0 || ORIG_REF_NAME==bd_f170_0_axis_mu12_0_0} -quiet] -quiet

# IP: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_17/bd_f170_0_axis_mu13_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f170_0_axis_mu13_0_0 || ORIG_REF_NAME==bd_f170_0_axis_mu13_0_0} -quiet] -quiet

# IP: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_18/bd_f170_0_axis_dbg_sync_2_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f170_0_axis_dbg_sync_2_0 || ORIG_REF_NAME==bd_f170_0_axis_dbg_sync_2_0} -quiet] -quiet

# IP: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_19/bd_f170_0_axis_dbg_sync_3_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f170_0_axis_dbg_sync_3_0 || ORIG_REF_NAME==bd_f170_0_axis_dbg_sync_3_0} -quiet] -quiet

# IP: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_20/bd_f170_0_axis_dbg_sync_4_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f170_0_axis_dbg_sync_4_0 || ORIG_REF_NAME==bd_f170_0_axis_dbg_sync_4_0} -quiet] -quiet

# IP: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_21/bd_f170_0_axis_dbg_sync_5_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f170_0_axis_dbg_sync_5_0 || ORIG_REF_NAME==bd_f170_0_axis_dbg_sync_5_0} -quiet] -quiet

# IP: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_22/bd_f170_0_axis_dbg_sync_6_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f170_0_axis_dbg_sync_6_0 || ORIG_REF_NAME==bd_f170_0_axis_dbg_sync_6_0} -quiet] -quiet

# IP: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_23/bd_f170_0_tc_axis_mu0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f170_0_tc_axis_mu0_0 || ORIG_REF_NAME==bd_f170_0_tc_axis_mu0_0} -quiet] -quiet

# IP: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_24/bd_f170_0_cc_axis_mu0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f170_0_cc_axis_mu0_0 || ORIG_REF_NAME==bd_f170_0_cc_axis_mu0_0} -quiet] -quiet

# IP: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_25/bd_f170_0_cc_axis_mu1_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f170_0_cc_axis_mu1_0 || ORIG_REF_NAME==bd_f170_0_cc_axis_mu1_0} -quiet] -quiet

# IP: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_26/bd_f170_0_cc_axis_mu2_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f170_0_cc_axis_mu2_0 || ORIG_REF_NAME==bd_f170_0_cc_axis_mu2_0} -quiet] -quiet

# IP: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_27/bd_f170_0_cc_axis_mu3_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f170_0_cc_axis_mu3_0 || ORIG_REF_NAME==bd_f170_0_cc_axis_mu3_0} -quiet] -quiet

# IP: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_28/bd_f170_0_axis_itct_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f170_0_axis_itct_0 || ORIG_REF_NAME==bd_f170_0_axis_itct_0} -quiet] -quiet

# IP: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_29/bd_f170_0_axis_ila_pp_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f170_0_axis_ila_pp_0 || ORIG_REF_NAME==bd_f170_0_axis_ila_pp_0} -quiet] -quiet

# IP: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_30/bd_f170_0_axis_mem_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f170_0_axis_mem_0 || ORIG_REF_NAME==bd_f170_0_axis_mem_0} -quiet] -quiet

# XDC: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_4/axis_mu_v1_0/constraints/axis_mu_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_f170_0_axis_mu0_0_0 || ORIG_REF_NAME==bd_f170_0_axis_mu0_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_5/axis_mu_v1_0/constraints/axis_mu_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_f170_0_axis_mu1_0_0 || ORIG_REF_NAME==bd_f170_0_axis_mu1_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_6/axis_mu_v1_0/constraints/axis_mu_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_f170_0_axis_mu2_0_0 || ORIG_REF_NAME==bd_f170_0_axis_mu2_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_7/axis_mu_v1_0/constraints/axis_mu_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_f170_0_axis_mu3_0_0 || ORIG_REF_NAME==bd_f170_0_axis_mu3_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_8/axis_mu_v1_0/constraints/axis_mu_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_f170_0_axis_mu4_0_0 || ORIG_REF_NAME==bd_f170_0_axis_mu4_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_9/axis_mu_v1_0/constraints/axis_mu_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_f170_0_axis_mu5_0_0 || ORIG_REF_NAME==bd_f170_0_axis_mu5_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_10/axis_mu_v1_0/constraints/axis_mu_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_f170_0_axis_mu6_0_0 || ORIG_REF_NAME==bd_f170_0_axis_mu6_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_11/axis_mu_v1_0/constraints/axis_mu_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_f170_0_axis_mu7_0_0 || ORIG_REF_NAME==bd_f170_0_axis_mu7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_12/axis_mu_v1_0/constraints/axis_mu_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_f170_0_axis_mu8_0_0 || ORIG_REF_NAME==bd_f170_0_axis_mu8_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_13/axis_mu_v1_0/constraints/axis_mu_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_f170_0_axis_mu9_0_0 || ORIG_REF_NAME==bd_f170_0_axis_mu9_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_14/axis_mu_v1_0/constraints/axis_mu_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_f170_0_axis_mu10_0_0 || ORIG_REF_NAME==bd_f170_0_axis_mu10_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_15/axis_mu_v1_0/constraints/axis_mu_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_f170_0_axis_mu11_0_0 || ORIG_REF_NAME==bd_f170_0_axis_mu11_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_16/axis_mu_v1_0/constraints/axis_mu_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_f170_0_axis_mu12_0_0 || ORIG_REF_NAME==bd_f170_0_axis_mu12_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_17/axis_mu_v1_0/constraints/axis_mu_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_f170_0_axis_mu13_0_0 || ORIG_REF_NAME==bd_f170_0_axis_mu13_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_23/axis_mu_v1_0/constraints/axis_mu_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_f170_0_tc_axis_mu0_0 || ORIG_REF_NAME==bd_f170_0_tc_axis_mu0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_24/axis_mu_v1_0/constraints/axis_mu_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_f170_0_cc_axis_mu0_0 || ORIG_REF_NAME==bd_f170_0_cc_axis_mu0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_25/axis_mu_v1_0/constraints/axis_mu_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_f170_0_cc_axis_mu1_0 || ORIG_REF_NAME==bd_f170_0_cc_axis_mu1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_26/axis_mu_v1_0/constraints/axis_mu_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_f170_0_cc_axis_mu2_0 || ORIG_REF_NAME==bd_f170_0_cc_axis_mu2_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/ip/ip_27/axis_mu_v1_0/constraints/axis_mu_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_f170_0_cc_axis_mu3_0 || ORIG_REF_NAME==bd_f170_0_cc_axis_mu3_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/bd_0/bd_f170_0_ooc.xdc

# XDC: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/axis_ila_v1_2/constraints/axis_ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_ila_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/axis_ila_v1_2/constraints/axis_ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_ila_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/ip/axis_ila_2/axis_ila_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_ila_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
