# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /tools/Xilinx/Vivado/2023.1/data/xhub/ced/XilinxCEDStore/ced/Xilinx/IPI/Versal_ACAP_CPM_PCIE_PIO_Design/cpm5_pcie_pio/constraints/top_impl.xdc

# Block Designs: bd/exerciser/exerciser.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==exerciser || ORIG_REF_NAME==exerciser} -quiet] -quiet

# IP: bd/exerciser/ip/exerciser_versal_cips_0_0/exerciser_versal_cips_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==exerciser_versal_cips_0_0 || ORIG_REF_NAME==exerciser_versal_cips_0_0} -quiet] -quiet

# Block Designs: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/bd/exerciser/ip/exerciser_versal_cips_0_0/bd_0/bd_6f6a.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_6f6a || ORIG_REF_NAME==bd_6f6a} -quiet] -quiet

# IP: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/bd/exerciser/ip/exerciser_versal_cips_0_0/bd_0/ip/ip_0/bd_6f6a_pspmc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_6f6a_pspmc_0_0 || ORIG_REF_NAME==bd_6f6a_pspmc_0_0} -quiet] -quiet

# IP: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/bd/exerciser/ip/exerciser_versal_cips_0_0/bd_0/ip/ip_0/ip_0/versal_cips_ps_vip_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==versal_cips_ps_vip_0 || ORIG_REF_NAME==versal_cips_ps_vip_0} -quiet] -quiet

# IP: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/bd/exerciser/ip/exerciser_versal_cips_0_0/bd_0/ip/ip_1/bd_6f6a_cpm_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_6f6a_cpm_0_0 || ORIG_REF_NAME==bd_6f6a_cpm_0_0} -quiet] -quiet

# IP: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/bd/exerciser/ip/exerciser_versal_cips_0_0/bd_0/ip/ip_1/ip_1/bd_6f6a_cpm_0_0_gt_quad_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_6f6a_cpm_0_0_gt_quad_3 || ORIG_REF_NAME==bd_6f6a_cpm_0_0_gt_quad_3} -quiet] -quiet

# IP: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/bd/exerciser/ip/exerciser_versal_cips_0_0/bd_0/ip/ip_1/ip_0/bd_6f6a_cpm_0_0_gt_quad_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_6f6a_cpm_0_0_gt_quad_2 || ORIG_REF_NAME==bd_6f6a_cpm_0_0_gt_quad_2} -quiet] -quiet

# XDC: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/bd/exerciser/ip/exerciser_versal_cips_0_0/bd_0/ip/ip_0/bd_6f6a_pspmc_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_6f6a_pspmc_0_0 || ORIG_REF_NAME==bd_6f6a_pspmc_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/bd/exerciser/ip/exerciser_versal_cips_0_0/bd_0/ip/ip_0/pspmc_v1_3/constraints/usr_constraints.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_6f6a_pspmc_0_0 || ORIG_REF_NAME==bd_6f6a_pspmc_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/bd/exerciser/ip/exerciser_versal_cips_0_0/bd_0/ip/ip_1/ip_1/synth/bd_6f6a_cpm_0_0_gt_quad_3_ooc.xdc

# XDC: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/bd/exerciser/ip/exerciser_versal_cips_0_0/bd_0/ip/ip_1/ip_1/bd_6f6a_cpm_0_0_gt_quad_3.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_6f6a_cpm_0_0_gt_quad_3 || ORIG_REF_NAME==bd_6f6a_cpm_0_0_gt_quad_3} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/bd/exerciser/ip/exerciser_versal_cips_0_0/bd_0/ip/ip_1/ip_0/synth/bd_6f6a_cpm_0_0_gt_quad_2_ooc.xdc

# XDC: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/bd/exerciser/ip/exerciser_versal_cips_0_0/bd_0/ip/ip_1/ip_0/bd_6f6a_cpm_0_0_gt_quad_2.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_6f6a_cpm_0_0_gt_quad_2 || ORIG_REF_NAME==bd_6f6a_cpm_0_0_gt_quad_2} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/bd/exerciser/ip/exerciser_versal_cips_0_0/bd_0/ip/ip_1/ip_cpm5.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_6f6a_cpm_0_0 || ORIG_REF_NAME==bd_6f6a_cpm_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/bd/exerciser/ip/exerciser_versal_cips_0_0/bd_0/ip/ip_1/synth/bd_6f6a_cpm_0_0_ooc.xdc

# XDC: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/bd/exerciser/ip/exerciser_versal_cips_0_0/bd_0/bd_6f6a_ooc.xdc

# XDC: /root/xuguo/xilinx_pro/vpk120/versal_pcie_cpm5_exerciser/versal_pcie_cpm5_exerciser.gen/sources_1/bd/exerciser/exerciser_ooc.xdc
